In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [93]:
df= pd.read_excel(r'DistanciasCiudades.xlsx', engine='openpyxl')
tab_conf= df.to_numpy()[0:18]

In [117]:
#Generacion de la población
class Poblacion:
    def __init__(self, num_pob, num_gen, dataf):
        self.num_pob= num_pob
        self.num_gen= num_gen
        self.tabla= dataf
        self.CreacionPoblacion()
        self.AcomodoPob()

    def CreacionPoblacion(self):
        self.pobl= np.empty(self.num_pob, dtype= object)
        for f in range(self.num_pob):
            self.pobl[f]= Individuo(self.num_pob, self.num_gen, self.tabla)

    def AcomodoPob(self):
        for n in range(self.num_pob):
            for m in range(self.num_pob-1):
                if self.pobl[m].apt > self.pobl[m+1].apt:
                    tmp= self.pobl[m]
                    self.pobl[m]= self.pobl[m+1]
                    self.pobl[m+1]= tmp

class Individuo:
    def __init__(self, num_pob, num_gen, tab):
        #self.num_pob= num_pob
        self.num_gen= num_gen
        self.tabla= tab
        self.CreacionIndividuo()
        self.Aptitud()
        
    def CreacionIndividuo(self):
        prueb= np.arange(self.num_gen, dtype= int)
        for c in range(self.num_gen, 0, -1):
            cam= np.random.randint(c)
            guard= prueb[c-1]
            prueb[c-1]= prueb[cam]
            prueb[cam]= guard
        self.indv= prueb

    def Aptitud(self):
        distancia= 0
        for c in range(self.num_gen-1):
            distancia= distancia+ self.tabla[self.indv[c], self.indv[c+1]]
        distancia= distancia+ self.tabla[self.indv[1], self.indv[c+1]]
        self.apt= distancia

In [118]:
n= Poblacion(50, 18, tab_conf)

In [119]:
for f in n.pobl:
    print(f.indv)

[ 1 15 17  2  8  5  6 11 13  7 16  0  9  3 14 10 12  4]
[12  8  9  2 15 14 16  4  1  7  5  0 13 11 17 10  3  6]
[ 2  7 11  0  5  8 12 16  9  1  3 14 15 10  4 13  6 17]
[ 1  3 10  8  2  7 14 15 16  4 11 13 12  6  5  9 17  0]
[12 14  8  9  7 11  6 17  5 15  4 16 10  3  2  0  1 13]
[ 4 15 17  5 16 12  8 10  7  6  9  0  1  2  3 11 13 14]
[13  8 14 10  6 11 17  9 16  1  7  0  3  2  5  4 12 15]
[ 1  7  5  9  3  8 14  4 16  0 11 12 15 10  6 13  2 17]
[14  1  0  5  3  8  6 12 13 11  9 16  7  2 17 10  4 15]
[12  6 11  3 13 16 15 17 10 14  2  7  0  5  1  9  4  8]
[12 13  9 15 16  1  2 14 17  6  5 11 10  8  0  4  3  7]
[ 5  1 16 13 14  6  2  7  3  8 11  0 17  4 10 15 12  9]
[16  7 10  2  3 13 15  4  6 12 17  1  0  9  8  5 14 11]
[14  3 17  1 16  8  7 13 15  2  9 10  6  0 12  4  5 11]
[14 17 10  7 12  4  5 15 16  8 11  6  0  1  2  9 13  3]
[13  4  1 10 17  8 14  3  7  6 12  9  0  2 11  5 16 15]
[14 12  9 17  0  1  4 15  8  2 10 13  6  5  7  3 11 16]
[15 12 17 11  7 16  5  3  1  8  9  6 14  0 13  2